### ISSUE TITLE
Embedding error

### ISSUE THREAD

**Issue by arminta7** [exoascension/vault-chat#2]
<img width="477" alt="Screenshot 2023-03-12 at 21 44 22" src="https://user-images.githubusercontent.com/7927356/224589701-2f80490f-75a1-4539-ab9f-ec5aa5870311.png">

**Comment by kristenbrann** [comment]
Thanks for reporting this!
Fixed in release 1.0.1

**Comment by arminta7** [comment]
Thanks! Can't update to the new release yet (using BRAT).

**Comment by kristenbrann** [comment]
Ahh, updated the manifest to reflect 1.0.1. Thank you so much! First time doing obsidian plugin dev :)
