### ISSUE TITLE
FR: exclude folder or file pattern

### ISSUE THREAD

**Issue by SimplGy** [exoascension/vault-chat#20]
I have at least a couple of files I really want to make sure never get sent to a third party API.

Can I exclude a folder like `_sensitive/*` or a file like `my_password_hints`?

**Comment by JoshuaElArbol** [comment]
Me encantaría también esta funcionalidad!

**Comment by cpaika** [comment]
Good idea, will add an exclusion filter.

**Comment by cpaika** [comment]
Added an exclusion path in settings, try it out and let us know what you think
